<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Target</name>
   <tag></tag>
   <elementGuidId>f6f9f6e3-bfb0-498a-99f3-4b9e03e8de11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body > app-root > main > loader > div > side-bar > div > div > ul:nth-child(3) > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>e43870a6-ba68-450a-855b-03d16928d1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1685984893662</value>
      <webElementGuid>43aafc00-5899-475d-92e4-5ff76735993a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
