<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_outputSign Out</name>
   <tag></tag>
   <elementGuidId>aade0ef4-7121-4d94-a6bf-66171d4eac51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-menu-panel-0']/div/div[2]/button[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-mdc-menu-item.mat-mdc-focus-indicator.mdc-list-item.st-user-menu--main-btn.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87165c93-5902-4b90-906a-6f573b65ec11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-menu-item mat-mdc-focus-indicator mdc-list-item st-user-menu--main-btn cdk-focused cdk-mouse-focused</value>
      <webElementGuid>72884ceb-4c1d-43b8-9cf6-6e2247bc6c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>0ff2c627-0a47-4906-8090-e5c26c8c9f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2cf69a46-b8a1-49d0-81f9-a1cc9f3700c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>61fbf753-e64d-4025-aa81-19fe3ebf494a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>outputSign Out</value>
      <webElementGuid>bc19a3e4-acf8-4cf3-a477-93f22b8655f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-0&quot;)/div[@class=&quot;mat-mdc-menu-content mdc-list ng-tns-c140-2&quot;]/div[@class=&quot;st-user-menu--main ng-tns-c140-2 ng-star-inserted&quot;]/button[@class=&quot;mat-mdc-menu-item mat-mdc-focus-indicator mdc-list-item st-user-menu--main-btn cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>da1b102e-281b-4be8-86e6-7c5882b461c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-0']/div/div[2]/button[7]</value>
      <webElementGuid>3e828566-7890-4f19-8c1d-789e6caa2329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/following::button[1]</value>
      <webElementGuid>622f3381-ec59-41b4-8108-b848b7b32f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::button[2]</value>
      <webElementGuid>9484e934-f515-4180-a1bb-511d6e93bb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[7]</value>
      <webElementGuid>ec04565e-fb52-4df1-94da-4fcde92ee197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'outputSign Out' or . = 'outputSign Out')]</value>
      <webElementGuid>86f31d95-7ca3-4aec-a516-0fe3507f4ac0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
