<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_edit_notifications_outlinedNotifications</name>
   <tag></tag>
   <elementGuidId>ff292721-31f9-4bc4-9cfb-4834f811136e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-menu-panel-0']/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-mdc-menu-item.mat-mdc-focus-indicator.mdc-list-item.st-user-menu--main-btn.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b973736b-dbc8-4862-90bc-42e0c498a446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-menu-item mat-mdc-focus-indicator mdc-list-item st-user-menu--main-btn cdk-focused cdk-mouse-focused</value>
      <webElementGuid>1ba69765-dd3b-4b7f-9955-fdd6dadd3660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>7f5504d9-0fd8-4c37-a06f-d6eef0351983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7b5d98ff-3204-48bd-bb09-cfdc97347004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b8ca04b9-6d98-4a6b-92dd-765de8208d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> edit_notifications_outlinedNotifications</value>
      <webElementGuid>1f423c97-ff93-4121-8827-68f1f569e1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-0&quot;)/div[@class=&quot;mat-mdc-menu-content mdc-list ng-tns-c140-2&quot;]/div[@class=&quot;st-user-menu--main ng-tns-c140-2 ng-star-inserted&quot;]/button[@class=&quot;mat-mdc-menu-item mat-mdc-focus-indicator mdc-list-item st-user-menu--main-btn cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>5f536d76-0f51-4495-9a89-a6ebe5653b9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-0']/div/div[2]/button</value>
      <webElementGuid>f4377093-0656-45f4-a68a-646270dfbcd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doe1 Jane'])[1]/following::button[1]</value>
      <webElementGuid>855e1a6d-648a-4f15-9c84-1e8a6f96014d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optional'])[1]/following::button[3]</value>
      <webElementGuid>8d4eceed-dafc-4b92-aa58-f3c3217b010d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region and Language'])[1]/preceding::button[1]</value>
      <webElementGuid>5a7157cc-4a08-4d64-bda5-9e9f15a58e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/button</value>
      <webElementGuid>85fc9aeb-6005-45be-869f-291283bdd36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' edit_notifications_outlinedNotifications' or . = ' edit_notifications_outlinedNotifications')]</value>
      <webElementGuid>4e156fbf-e271-4fee-a215-c5261506ad6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
