<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Daily (1)</name>
   <tag></tag>
   <elementGuidId>abf5d150-209f-4b46-8119-e967c70817b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mdl-list__item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[3]/following::div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43cae9c2-e507-4904-be44-42eb5ffb8e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdl-list__item</value>
      <webElementGuid>f87e10a1-1176-4ffe-8236-1070ec628973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daily</value>
      <webElementGuid>b9ef4683-b55c-44b2-8536-180a1a22b3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;playbook-theme multiple-products&quot;]/app-root[1]/main[@class=&quot;ng-star-inserted&quot;]/loader[1]/div[1]/main-content[@class=&quot;otouch&quot;]/div[@class=&quot;main-content sidemenu-shrinked&quot;]/manage-publication-channels[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;data-container-wrapper&quot;]/loader[1]/div[@class=&quot;scroll-container&quot;]/pane-container[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;is-expanded&quot;]/div[@class=&quot;relative left item-container ng-star-inserted&quot;]/div[@class=&quot;left mleft20 main-info-container&quot;]/div[@class=&quot;w70 left row&quot;]/div[@class=&quot;left ellipsis col single-page ng-star-inserted&quot;]/mdl-select[@class=&quot;mdl-select has-placeholder ng-untouched ng-valid ng-star-inserted ng-dirty&quot;]/div[@class=&quot;mdl-textfield is-upgraded is-focused&quot;]/mdl-popover[@class=&quot;mdl-popover is-visible&quot;]/div[@class=&quot;mdl-list mdl-shadow--6dp&quot;]/mdl-option[@class=&quot;mdl-option__container ng-star-inserted&quot;]/div[@class=&quot;mdl-list__item&quot;]</value>
      <webElementGuid>d6d6e690-5f55-4fd0-b316-09f427214263</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[3]/following::div[2]</value>
      <webElementGuid>32ad7df2-20c1-412f-8675-77a025d49406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[2]/following::div[5]</value>
      <webElementGuid>a5b26bfb-55c9-4bdc-9f49-aa957465ee24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supports Revisions'])[2]/preceding::div[3]</value>
      <webElementGuid>54c7e021-22a5-4887-810e-0bf120bb3177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mdl-option/div</value>
      <webElementGuid>17f660c9-dde6-4f0c-b5bb-48395140873c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Daily' or . = 'Daily')]</value>
      <webElementGuid>16d57bca-06bf-40c4-a7a3-f45dab2d050d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
