<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_6</name>
   <tag></tag>
   <elementGuidId>aacec65e-8938-42b2-a656-ee1320d85e9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body > app-root > main > loader > div > main-content > div.main-content.sidemenu-shrinked > manage-publication-channels > div > loader > div > pane-container > table > tr > td:nth-child(3) > div.pane-counter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/main/loader/div/main-content/div[2]/manage-publication-channels/div/loader/div/pane-container/table/tr/td[3]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2eb1018a-df0f-4716-b435-6a4f8c41b786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pane-counter ng-star-inserted</value>
      <webElementGuid>71563566-4c30-4db7-bfb7-dd5ec1fac312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>45625224-0df5-46cc-8be4-d12b5cc48685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;playbook-theme multiple-products&quot;]/app-root[1]/main[@class=&quot;ng-star-inserted&quot;]/loader[1]/div[1]/main-content[@class=&quot;otouch&quot;]/div[@class=&quot;main-content sidemenu-shrinked&quot;]/manage-publication-channels[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;data-container-wrapper&quot;]/loader[1]/div[@class=&quot;scroll-container&quot;]/pane-container[2]/table[@class=&quot;pane-container mtop10 mright5 ng-star-inserted&quot;]/tr[1]/td[3]/div[@class=&quot;pane-counter ng-star-inserted&quot;]</value>
      <webElementGuid>17a5792b-7d66-40ef-b631-f236a869aa91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Publication Channels'])[1]/following::div[2]</value>
      <webElementGuid>a51ce6b0-e6d6-4bb3-97ce-21302da617e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[7]</value>
      <webElementGuid>73dc7663-e481-48d7-9a5b-42b631483bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/preceding::div[2]</value>
      <webElementGuid>9ad2df3d-af44-4330-8f2d-a3a33c945fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workflow Action'])[2]/preceding::div[3]</value>
      <webElementGuid>a8575b47-7d46-4c40-8e33-d0a00898ff83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='6']/parent::*</value>
      <webElementGuid>4659f292-2911-45e4-8437-d3c2692e3e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//pane-container[2]/table/tr/td[3]/div[2]</value>
      <webElementGuid>bd2ddbfb-a594-492f-981b-6329ae5ff3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '6' or . = '6')]</value>
      <webElementGuid>9baef85c-6992-4a20-8f3e-f78651fdf549</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
