<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_System Administrator_planning-view-item_beac0c</name>
   <tag></tag>
   <elementGuidId>60387172-17fe-4085-8258-6e1c54e47631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[11]/planning-view-item/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e41db7a-306d-411c-93bd-daf1ca765a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>planning-view-item-drag-handle drag-handle</value>
      <webElementGuid>7d0f94c1-0229-4fb1-9c38-d170b296c88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;playbook-theme multiple-products&quot;]/app-root[1]/main[@class=&quot;ng-star-inserted&quot;]/loader[1]/div[1]/main-content[@class=&quot;otouch&quot;]/div[@class=&quot;main-content sidemenu-expanded&quot;]/planning-views[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;planning-views-container&quot;]/div[@class=&quot;data-container-wrapper-filter-overlay data-container-wrapper-filter-collapsed&quot;]/div[@class=&quot;left oauto data-container scrollable data-container-filter-overlay data-container-filter-collapsed&quot;]/loader[1]/div[1]/div[@class=&quot;ng-star-inserted&quot;]/pane-container[1]/div[@class=&quot;is-expanded&quot;]/div[@class=&quot;planning-view-item-container ng-star-inserted&quot;]/planning-view-item[1]/div[@class=&quot;planning-view-item&quot;]/div[@class=&quot;planning-view-item-drag-handle drag-handle&quot;]</value>
      <webElementGuid>6f4b1f2f-de86-41aa-9eb2-acb27520eb27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/planning-view-item/div/div</value>
      <webElementGuid>50598d2b-a545-43de-95f8-6d6aceea61f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
