<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AP STORYTELLINGUsernamePasswordvisibili_ea0272</name>
   <tag></tag>
   <elementGuidId>596435ef-2a4e-472f-b193-13d7e1e9638f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.st-login-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ee2c799-b47f-4338-9128-e8f7943b7d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>st-login-container</value>
      <webElementGuid>4d8026af-cd71-4e06-a305-dda0f213eb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AP STORYTELLINGUsernamePasswordvisibility_offRemember Me Login or Login with Google  Login with Azure  Login with Okta  © Associated Press. All rights reserved. </value>
      <webElementGuid>2293cd49-ec4b-4af3-ac8e-209665021aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;playbook-theme&quot;]/app-root[@class=&quot;st-app-component&quot;]/login[@class=&quot;st-login ng-star-inserted&quot;]/div[@class=&quot;st-login-container&quot;]</value>
      <webElementGuid>3c2c5ce1-f7c4-4be2-a339-610309a3e135</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>fe2a6a94-eb99-42d5-9996-0d1e5b0a6c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AP STORYTELLINGUsernamePasswordvisibility_offRemember Me Login or Login with Google  Login with Azure  Login with Okta  © Associated Press. All rights reserved. ' or . = 'AP STORYTELLINGUsernamePasswordvisibility_offRemember Me Login or Login with Google  Login with Azure  Login with Okta  © Associated Press. All rights reserved. ')]</value>
      <webElementGuid>5805023b-fbaa-4bed-8d82-a3a1f62c1832</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
