<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_keyboard_arrow_down_left ellipsis col s_7ade5b</name>
   <tag></tag>
   <elementGuidId>ed433afd-67ab-4087-b826-75d319028d10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.planning-view-item-selected.fs14.icon-FavoriteNotSelected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dfbd15f5-0ba1-4558-ab0a-6a8572d4a3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>planning-view-item-selected fs14 icon-FavoriteNotSelected</value>
      <webElementGuid>0ad9b2e4-5754-4078-b00e-4942214165ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>cd229a3f-26a6-45ed-9bdd-3eccedeadbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;playbook-theme multiple-products&quot;]/app-root[1]/main[@class=&quot;ng-star-inserted&quot;]/loader[1]/div[1]/main-content[@class=&quot;otouch&quot;]/div[@class=&quot;main-content sidemenu-expanded&quot;]/planning-views[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;planning-views-container&quot;]/div[@class=&quot;data-container-wrapper-filter-overlay data-container-wrapper-filter-collapsed&quot;]/div[@class=&quot;left oauto data-container scrollable data-container-filter-overlay data-container-filter-collapsed&quot;]/loader[1]/div[1]/div[@class=&quot;ng-star-inserted&quot;]/pane-container[1]/div[@class=&quot;is-expanded&quot;]/div[@class=&quot;planning-view-item-container ng-star-inserted&quot;]/planning-view-item[1]/div[@class=&quot;planning-view-item&quot;]/div[@class=&quot;planning-view-item-buttons-container&quot;]/div[@class=&quot;planning-view-item-selected fs14 icon-FavoriteNotSelected&quot;]</value>
      <webElementGuid>66789d52-3f56-4808-8dfd-373d18950440</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div</value>
      <webElementGuid>ddead07d-9741-46ff-8b5f-3a3547ccaf80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[3]/following::div[2]</value>
      <webElementGuid>8c07104c-aae5-446d-ae41-0a9b9ba7f59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[2]/following::div[5]</value>
      <webElementGuid>049aba2d-2aee-4aa8-a2e8-73eeecbdf532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[4]/preceding::div[6]</value>
      <webElementGuid>b3de5bbe-4fd3-4314-a04c-4e1111310162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[5]/preceding::div[9]</value>
      <webElementGuid>05c98711-f5f0-4c01-b49d-82809bcc1709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[4]</value>
      <webElementGuid>7e3dbce8-d721-4ddd-a5dc-a917f0316ffc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
