<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Language</name>
   <tag></tag>
   <elementGuidId>1fa4a213-5a7d-409f-9db4-4e0bcf8edb64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/main/loader/div/top-bar-user-menu/div/div[2]/table/tr/td[3]/div/div[5][count(. | //*[(text() = 'Language' or . = 'Language')]) = count(//*[(text() = 'Language' or . = 'Language')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/main/loader/div/top-bar-user-menu/div/div[2]/table/tr/td[3]/div/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>54413e35-1ad9-40e1-9f12-e13c82abbee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mleft30 mright20 mtop10 fs12 gray</value>
      <webElementGuid>649c3a53-2ef9-4557-8d76-c6c755d2a3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>bf2b4138-1bb3-4d43-82d1-9f9153d13725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Language</value>
      <webElementGuid>763ff127-47a8-46ef-815f-8f6b726813fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/main/loader/div/top-bar-user-menu/div/div[2]/table/tr/td[3]/div/div[5]</value>
      <webElementGuid>73d7ce29-5733-4480-ac61-f11fbe9ac667</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[5]/following::div[2]</value>
      <webElementGuid>8a0a6d40-a628-466f-910a-23f124fdcb53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Time Zone'])[1]/following::div[4]</value>
      <webElementGuid>0ccaa95b-7c5c-4a02-a5f6-ee040095035c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[6]/preceding::div[1]</value>
      <webElementGuid>1554d1fb-7866-4ea7-9580-84ec208a2a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Language']/parent::*</value>
      <webElementGuid>8ec42b71-12b1-444c-be2d-e59df0a542eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div[5]</value>
      <webElementGuid>7a7d67ea-eb7b-4c79-8536-741941231020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Language' or . = 'Language')]</value>
      <webElementGuid>aed8a364-4f4d-4594-a9c1-ec1ca56d66b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
