<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3cf17b32-3681-44ff-8b6c-c8315826d8a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>687fcb16-81bb-471c-942f-7d09afea234e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>d2196b51-e9ab-4562-9fbf-78262c42dee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>2013e098-ca2e-4ae5-8ffd-18fed85f30f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>2fed07da-fe0d-49c0-b2d0-e0e3f993bc13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>833961b8-05ad-4061-aa75-6049dd597a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-img</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>05bc782e-74ba-4e7f-915d-6a0337c132a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://LONENPSDEVZL30.ap-storytelling.com/NOMWebServices3JSON/api/Avatar?userid=JANEDOE1&amp;userToken=null</value>
      <webElementGuid>fb99fe3c-8cf4-4152-9f32-838fcefc85cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;playbook-theme multiple-products&quot;]/app-root[@class=&quot;st-app-component&quot;]/main[@class=&quot;st-main ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container st-main-container mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/div[@class=&quot;st-main-content-container&quot;]/top-bar[@class=&quot;st-top-bar&quot;]/mat-toolbar[@class=&quot;mat-toolbar st-top-bar-toolbar mat-toolbar-multiple-rows&quot;]/mat-toolbar-row[@class=&quot;mat-toolbar-row&quot;]/div[@class=&quot;st-top-bar-button-group&quot;]/top-bar-user-menu[1]/avatar[@class=&quot;st-avatar mat-mdc-menu-trigger&quot;]/img[1]</value>
      <webElementGuid>e642bc24-f56b-4bdb-8812-db0f14c07b4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>b137a55e-aca4-4ba7-b2f6-cfa496ac719c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://LONENPSDEVZL30.ap-storytelling.com/NOMWebServices3JSON/api/Avatar?userid=JANEDOE1&amp;userToken=null']</value>
      <webElementGuid>6a8803d7-cc0c-4037-844b-26414903b638</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
