<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Save_mdl-textfield-2 (2)</name>
   <tag></tag>
   <elementGuidId>db2fb131-6432-4424-9f34-0f7faf70414f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mdl-textfield-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mdl-textfield-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>783fccd2-296e-4c8a-9c4d-fd34a641bdac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdl-textfield__input ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>b2144809-15f1-408c-b81c-24bd092c9956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e4d95af7-ebd3-49aa-9a61-1ba94810b95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdl-textfield-2</value>
      <webElementGuid>db1dbcd7-b404-4585-bdd1-9860dd7ce9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.*</value>
      <webElementGuid>e0118d32-4ef7-4bfc-a7c1-4c021f369ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdl-textfield-2&quot;)</value>
      <webElementGuid>42db228e-e2fe-4989-84da-12ef6d44ca30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mdl-textfield-2']</value>
      <webElementGuid>5378348e-8bf3-4b3d-91a5-f26aea17aef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/mdl-textfield/div/input</value>
      <webElementGuid>e4a60efc-04d6-4737-9869-6e2e32bdf87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mdl-textfield-2']</value>
      <webElementGuid>adc592db-87eb-40c1-b049-9047211f8c1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
