<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AP STORYTELLING_mdl-textfield-4eef9f4e</name>
   <tag></tag>
   <elementGuidId>5ab1dbbb-e469-437d-8917-5087388f9fa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mdl-textfield-4eef9f4e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mdl-textfield-4eef9f4e']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc9e07c3-c17a-4589-94bf-e8532a04face</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>763c0b7d-cdd1-44cb-8e38-8ce4622a4fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdl-textfield__input</value>
      <webElementGuid>1fa39bad-af41-4dbb-a1fd-d1c7452143a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdl-textfield-4eef9f4e</value>
      <webElementGuid>bd5aae99-e679-4a98-a824-abd9151ae9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdl-textfield-4eef9f4e&quot;)</value>
      <webElementGuid>6cdaa650-b2c7-457b-bc63-fd75e4661937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mdl-textfield-4eef9f4e']</value>
      <webElementGuid>3a4cc6a0-4e66-486e-b357-3892d7eb3135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9bf580c0-3721-4488-828f-440f6257106a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mdl-textfield-4eef9f4e']</value>
      <webElementGuid>de70e5c6-059a-4549-8733-68e288668948</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
