<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Save_mdl-textfield-2 (3)</name>
   <tag></tag>
   <elementGuidId>2f018b15-4abe-4da0-b7ce-8706bb4d53fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mdl-textfield-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mdl-textfield-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b428ba41-c4cd-4b7c-b057-458c95e87a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdl-textfield__input ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>a9f755f0-45b5-4d50-8233-59f46b044a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d05c23b-4da4-4173-97b4-43c846c4c365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdl-textfield-2</value>
      <webElementGuid>202a790e-92a5-4ca2-8df4-ba2a6325ba6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.*</value>
      <webElementGuid>c02dce88-7293-48f7-8378-8789fa8d8053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdl-textfield-2&quot;)</value>
      <webElementGuid>52b1df4a-ee4e-4aff-9c1d-d3b00c72cdf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mdl-textfield-2']</value>
      <webElementGuid>23f9420a-9354-4a02-be5c-31b091e094d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/mdl-textfield/div/input</value>
      <webElementGuid>633c5c30-3a10-41ef-8254-c02be626bd6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mdl-textfield-2']</value>
      <webElementGuid>38bd52e0-41f1-4c80-b56f-e4d3498e0ce6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
