<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_keyboard_arrow_down_mdl-textfield-afc25cbc (1)</name>
   <tag></tag>
   <elementGuidId>33b9ab5f-4a99-4946-aea5-e646e5c333e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mdl-textfield-afc25cbc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mdl-textfield-afc25cbc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ea0ae6a-d0c6-434d-aa23-8705a1eae3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>eb60fdb5-8dd8-48f5-ba2f-bb2aa2200e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdl-textfield__input</value>
      <webElementGuid>22b5b0c9-cea5-4f90-87b7-1c4a54765db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>2d118b29-bc53-45cd-adba-c24586df27f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdl-textfield-afc25cbc</value>
      <webElementGuid>38db13b5-5823-4251-838c-f7d05488dd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdl-textfield-afc25cbc&quot;)</value>
      <webElementGuid>06012ad2-7bd5-4530-bf08-7fad1b5f173a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mdl-textfield-afc25cbc']</value>
      <webElementGuid>f8008c4e-922b-4d71-8ea1-701326fb67a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mdl-select/div/input</value>
      <webElementGuid>ffb54dc0-21db-4480-90aa-9820514db5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Type' and @id = 'mdl-textfield-afc25cbc']</value>
      <webElementGuid>aed6d298-e0f7-4ea1-864b-f547503dfc94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
