<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Save_mdl-textfield-2</name>
   <tag></tag>
   <elementGuidId>df560241-0522-40a8-99fe-72e4f5c382f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mdl-textfield-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mdl-textfield-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff34bd91-fed1-4adf-864e-5668fa6d7c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdl-textfield__input ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>8f757c27-0bf2-44db-aea3-4b4356087146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e327069-4097-4344-9290-3b72ed81b14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mdl-textfield-2</value>
      <webElementGuid>a28cf01c-6394-4bbe-81fb-f2be68ca5cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>.*</value>
      <webElementGuid>776527f0-1908-49a0-90c4-5371a67f4b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mdl-textfield-2&quot;)</value>
      <webElementGuid>14b67a7d-78ee-46e9-a984-1d3e469c3c02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mdl-textfield-2']</value>
      <webElementGuid>bea00302-88c9-43cf-8f40-cfa617e39090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/mdl-textfield/div/input</value>
      <webElementGuid>c4368a32-5f88-4f40-96f8-b1f58b712fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mdl-textfield-2']</value>
      <webElementGuid>4c9bf41a-c135-4c64-b5d4-c2952072dfeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
