<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_more_horiz</name>
   <tag></tag>
   <elementGuidId>d56c462a-62fd-4762-8bd4-b2f72b64dd3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainPanel']/div[4]/playbook-card-view/div/div/div/card-group/pane-container/div[3]/div[2]/div/assignment/div/div/div[5]/div[2]/mat-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainPanel > div:nth-child(4) > playbook-card-view > div > div > div > card-group > pane-container > div.is-expanded > div:nth-child(3) > topic-item > div.mbottom2.list-item.web.is-not-selected.drag-handle.ng-star-inserted > div.lower-card > div.side-menu.ng-star-inserted > div > div.d-inline-block > mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>467b94ce-127f-4b04-ab4e-3118edc23424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>db72cdcf-a134-4136-8142-fd365463c6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b5547d4-758c-4def-b179-9e3a14ebdc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons mat-icon-no-color</value>
      <webElementGuid>be4b06ea-5e4e-49f6-ae6a-3317ee022233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>79ed186c-37ff-4b1f-9deb-25cdfe0b9cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> more_horiz </value>
      <webElementGuid>4f112614-2379-4595-8b2d-bf5bc0f3549e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainPanel&quot;)/div[@class=&quot;ng-star-inserted&quot;]/playbook-card-view[1]/div[@class=&quot;list-items-container left-scrollable otouch ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/card-group[1]/pane-container[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;is-expanded&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mbottom10 assignment-list-item mleft5 ng-star-inserted&quot;]/assignment[1]/div[@class=&quot;ptop10 drag-handle assignment-block-list ng-star-inserted&quot;]/div[@class=&quot;assignment-container&quot;]/div[@class=&quot;more-menu d-flex align-items-end ng-star-inserted&quot;]/div[@class=&quot;d-inline-block&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons mat-icon-no-color&quot;]</value>
      <webElementGuid>7e1b4d69-775c-453c-8658-09517fce5fb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainPanel']/div[4]/playbook-card-view/div/div/div/card-group/pane-container/div[3]/div[2]/div/assignment/div/div/div[5]/div[2]/mat-icon</value>
      <webElementGuid>220fd2e6-1762-485a-872d-8bad120d85b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Changed: 24 minutes ago'])[1]/following::mat-icon[1]</value>
      <webElementGuid>a57ce3ee-ac1c-47ea-917c-588393d78492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[5]/following::mat-icon[1]</value>
      <webElementGuid>2c22c049-0b63-46e4-8fa7-d2458ada750b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slug'])[4]/preceding::mat-icon[1]</value>
      <webElementGuid>8f93d877-456e-4ccc-b3bd-269f212b23a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Administrator'])[2]/preceding::mat-icon[1]</value>
      <webElementGuid>fd55b78b-1064-4a1a-afb0-2460050feeba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='more_horiz']/parent::*</value>
      <webElementGuid>81093a19-25ed-4ca8-8c96-8e0be142aa2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-icon</value>
      <webElementGuid>ef086b08-8052-459d-b244-259de5d299d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = ' more_horiz ' or . = ' more_horiz ')]</value>
      <webElementGuid>2291e39d-c9f1-4903-b4ab-3a68e1449bff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
