<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-label_Username (1)</name>
   <tag></tag>
   <elementGuidId>4cba801c-ca5f-40ec-89d9-645f45eee8c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='mat-mdc-form-field-label-4']/mat-label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-label.ng-tns-c104-130</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-label</value>
      <webElementGuid>d623d391-3f37-4e66-88a8-48df578a42ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c104-130</value>
      <webElementGuid>1abb6575-83f9-4acb-bc82-d10589f41ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>07bcdf34-2859-436a-9b10-fd25842587d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-form-field-label-4&quot;)/mat-label[@class=&quot;ng-tns-c104-130&quot;]</value>
      <webElementGuid>fbcdfd1a-8e39-490f-9402-ed1f45fe3b22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='mat-mdc-form-field-label-4']/mat-label</value>
      <webElementGuid>dc8dae1e-f564-4f6e-b3c9-476f7327d602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP STORYTELLING'])[1]/following::mat-label[1]</value>
      <webElementGuid>32d28f94-aaed-4b5a-8ce6-9c68aadf10d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::mat-label[1]</value>
      <webElementGuid>6a7754c4-5131-4412-b35f-7d312fc772f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember my username on this device'])[1]/preceding::mat-label[2]</value>
      <webElementGuid>780db832-f46b-4e27-b609-13a017332139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Username']/parent::*</value>
      <webElementGuid>c760008f-2de7-44e5-a231-c6a0b85e94c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-label</value>
      <webElementGuid>0a8d9ca5-2dfe-4211-b99c-2b6262e02b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-label[(text() = 'Username' or . = 'Username')]</value>
      <webElementGuid>ff87dc87-24b3-46a4-aefd-3521a9c35477</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
