<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_more_horiz</name>
   <tag></tag>
   <elementGuidId>d56c462a-62fd-4762-8bd4-b2f72b64dd3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.material-icons.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainPanel']/div[4]/playbook-card-view/div/div/div/card-group/pane-container/div[3]/div[2]/div/assignment/div/div/div[5]/div[2]/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>14a4008c-e760-4060-aae0-a819a3ee79bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0733a1ae-39db-4a43-b371-76e33404f21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8f2a59d9-ff2c-4d17-87be-4599d8f062d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons mat-icon-no-color</value>
      <webElementGuid>b3b59cf2-fdf0-42c9-8899-4d0dafb8430d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>1bccc08a-c398-4a47-be76-ab5655c09a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> more_horiz </value>
      <webElementGuid>12cdabb9-96c6-4b96-808e-40c708551943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainPanel&quot;)/div[@class=&quot;ng-star-inserted&quot;]/playbook-card-view[1]/div[@class=&quot;list-items-container left-scrollable otouch ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/card-group[1]/pane-container[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;is-expanded&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mbottom10 assignment-list-item mleft5 ng-star-inserted&quot;]/assignment[1]/div[@class=&quot;ptop10 drag-handle assignment-block-list ng-star-inserted&quot;]/div[@class=&quot;assignment-container&quot;]/div[@class=&quot;more-menu d-flex align-items-end ng-star-inserted&quot;]/div[@class=&quot;d-inline-block&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons mat-icon-no-color&quot;]</value>
      <webElementGuid>0c435153-e865-4ea3-930e-5a1d9e8d733c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainPanel']/div[4]/playbook-card-view/div/div/div/card-group/pane-container/div[3]/div[2]/div/assignment/div/div/div[5]/div[2]/mat-icon</value>
      <webElementGuid>6cd6a2e0-81c2-422a-a54c-66143d22c925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Changed: 24 minutes ago'])[1]/following::mat-icon[1]</value>
      <webElementGuid>5508dfef-1432-4b12-98a7-bde8e410513e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[5]/following::mat-icon[1]</value>
      <webElementGuid>96a06638-a1ee-4ab3-8b69-797abf1d2f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slug'])[4]/preceding::mat-icon[1]</value>
      <webElementGuid>1333a266-3f31-4800-9134-8b1db58c98a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Administrator'])[2]/preceding::mat-icon[1]</value>
      <webElementGuid>e4a5d8e4-b782-43f1-b6c7-a0b66108ff3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='more_horiz']/parent::*</value>
      <webElementGuid>f55c84c0-f086-4dd0-9991-fbb63645b687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-icon</value>
      <webElementGuid>61165bc8-adea-4a5c-883a-ee0566c8145a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = ' more_horiz ' or . = ' more_horiz ')]</value>
      <webElementGuid>13018b36-9a3b-4fc3-a964-5e736d36c3ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
