<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Section Title_icon-ApplicationMenu hand fs22</name>
   <tag></tag>
   <elementGuidId>6ba0cda2-f0fd-462a-9b4b-dd68a03ce777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//top-bar/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon-ApplicationMenu.hand.fs22</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7d22fc92-3312-41aa-874a-b9da2366082f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-ApplicationMenu hand fs22</value>
      <webElementGuid>bee21520-36e5-49de-8e45-9c03c3ce272e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;playbook-theme multiple-products&quot;]/app-root[1]/main[@class=&quot;ng-star-inserted&quot;]/loader[1]/div[1]/top-bar[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;top-bar-container fixed team-settings&quot;]/div[@class=&quot;hamburger-menu left mright10&quot;]/span[@class=&quot;icon-ApplicationMenu hand fs22&quot;]</value>
      <webElementGuid>008036e3-bc15-4daa-ba79-ccb3b1698530</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//top-bar/div/div/span</value>
      <webElementGuid>faea9f5a-2d43-4ce7-a777-a8c119439653</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
