<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password_mat-mdc-button-touch-target</name>
   <tag></tag>
   <elementGuidId>cc55c896-9923-4560-8402-b985728124f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mdl-checkbox__tick-outline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d6d6e6db-a850-4187-a76c-0d28f4c3f184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdl-checkbox__tick-outline</value>
      <webElementGuid>031096e2-ae94-4c80-a8d9-cceb17f0bd53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;playbook-theme multiple-products&quot;]/app-root[1]/main[@class=&quot;ng-star-inserted&quot;]/loader[1]/div[1]/main-content[@class=&quot;otouch&quot;]/div[@class=&quot;main-content sidemenu-shrinked&quot;]/manage-publication-channels[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;data-container-wrapper&quot;]/loader[1]/div[@class=&quot;scroll-container&quot;]/pane-container[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;is-expanded&quot;]/div[@class=&quot;relative left item-container ng-star-inserted&quot;]/div[@class=&quot;left mleft20 main-info-container&quot;]/div[@class=&quot;w70 left row&quot;]/div[@class=&quot;left ellipsis col single-page ng-star-inserted&quot;]/mdl-checkbox[@class=&quot;mdl-checkbox is-upgraded ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/span[@class=&quot;mdl-checkbox__box-outline&quot;]/span[@class=&quot;mdl-checkbox__tick-outline&quot;]</value>
      <webElementGuid>8974b20f-8d4f-4844-92ad-b798b058785a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span</value>
      <webElementGuid>9f198809-c81d-41bb-b576-449df37d1f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]</value>
      <webElementGuid>1125df73-0858-44b2-bd9a-c0be98990822</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
