<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_View3 assignments_icon-ApplicationMenu_ae05cc (4)</name>
   <tag></tag>
   <elementGuidId>c29ff656-7c48-4614-990e-256edd866c2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.icon-ApplicationMenu.hand.fs22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//top-bar/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8dd8b7e0-c859-4ceb-a66b-e030411bec71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-ApplicationMenu hand fs22</value>
      <webElementGuid>cfc41389-d1e8-4e82-bc74-785d65448cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;playbook-theme multiple-products&quot;]/app-root[1]/main[@class=&quot;ng-star-inserted&quot;]/loader[1]/div[1]/top-bar[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;top-bar-container fixed&quot;]/div[@class=&quot;hamburger-menu left mright10&quot;]/span[@class=&quot;icon-ApplicationMenu hand fs22&quot;]</value>
      <webElementGuid>853fbb97-63ed-49e9-9a50-ff1b4ff2f0f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//top-bar/div/div/span</value>
      <webElementGuid>a5470fe2-04a3-4a75-8205-a3c6be773af4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
