<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Help</name>
   <tag></tag>
   <elementGuidId>7a5d30ce-196e-43bf-a54f-e9c97577ed7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-menu-panel-0']/div/div[2]/button[5]/span/a/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span[title=&quot;Help&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a44b91fd-0532-4cbc-b926-466fc80464fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Help</value>
      <webElementGuid>05a7e5c3-2bf0-47f8-a886-149699fb1a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Help</value>
      <webElementGuid>e0ef82dd-1683-4a2d-9200-b07522594fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-0&quot;)/div[@class=&quot;mat-mdc-menu-content mdc-list ng-tns-c140-2&quot;]/div[@class=&quot;st-user-menu--main ng-tns-c140-2 ng-star-inserted&quot;]/button[@class=&quot;mat-mdc-menu-item mat-mdc-focus-indicator mdc-list-item st-user-menu--main-btn&quot;]/span[@class=&quot;mdc-list-item__primary-text&quot;]/a[@class=&quot;mat-mdc-menu-item mat-mdc-focus-indicator mdc-list-item st-user-menu--main-btn__link cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mdc-list-item__primary-text&quot;]/span[1]</value>
      <webElementGuid>1646964e-8269-45e1-9110-15e5969d7df7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-0']/div/div[2]/button[5]/span/a/span/span</value>
      <webElementGuid>81021645-51a9-4a65-841f-29aeb10bfe23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publication Channel'])[1]/following::span[3]</value>
      <webElementGuid>4ec804ba-1677-4479-88e2-323a4348c383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Members'])[1]/following::span[5]</value>
      <webElementGuid>1cf8b7fe-65fe-4755-9330-4a6670fcdf4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/preceding::span[1]</value>
      <webElementGuid>181ceba0-8a2d-4e92-9cc7-fe5fbaf9bf30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/preceding::span[3]</value>
      <webElementGuid>c31b8715-7327-4aee-81ea-66b56a323417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Help']/parent::*</value>
      <webElementGuid>ffdf718e-10e7-4fb7-aefa-08ff42cea93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span/span</value>
      <webElementGuid>b1382acf-0d97-4759-8438-97020756046e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Help' and (text() = 'Help' or . = 'Help')]</value>
      <webElementGuid>d9dc50c1-6d95-4291-b14f-e780436437f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
