<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_View3 assignments_icon-ApplicationMenu_ae05cc (3)</name>
   <tag></tag>
   <elementGuidId>0d16a57e-a565-43bf-97ff-0dfd715340f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.icon-ApplicationMenu.hand.fs22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//top-bar/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7eed6f67-acc2-4021-9efc-8c13bfada8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-ApplicationMenu hand fs22</value>
      <webElementGuid>9a3db282-1a94-483a-b80b-aaaa9ae4b37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;playbook-theme multiple-products&quot;]/app-root[1]/main[@class=&quot;ng-star-inserted&quot;]/loader[1]/div[1]/top-bar[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;top-bar-container fixed&quot;]/div[@class=&quot;hamburger-menu left mright10&quot;]/span[@class=&quot;icon-ApplicationMenu hand fs22&quot;]</value>
      <webElementGuid>b1828eed-7a5d-4501-8a91-63f0989fc175</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//top-bar/div/div/span</value>
      <webElementGuid>55d6a778-41f3-4144-bd24-ff0a5336ebe0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
