<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_keyboard_arrow_down</name>
   <tag></tag>
   <elementGuidId>4647e7bf-130b-4ae9-beab-14cd8c2f69b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainPanel']/div[2]/div[3]/div/div[2]/div/list-drop-down/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8eaf9024-d1bc-4815-ae9f-93599e917bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons left mleft5 pointer</value>
      <webElementGuid>f6346beb-3a67-45e7-9beb-03203f65eeea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>keyboard_arrow_down</value>
      <webElementGuid>5dad6189-4164-40b5-853e-2f304b9267bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainPanel&quot;)/div[@class=&quot;top-menu mtop10 row mx-0 flex-nowrap&quot;]/div[@class=&quot;top-container col px-0 ng-star-inserted&quot;]/div[@class=&quot;row justify-content-end align-items-center h-100 mx-0 flex-nowrap&quot;]/div[@class=&quot;d-flex flex-column flex-shrink-1 flex-nowrap min-w-0 ng-star-inserted&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center mright20 flex-shrink-1 flex-nowrap min-w-0&quot;]/list-drop-down[@class=&quot;mright5 d-flex flex-shrink-1 flex-nowrap min-w-0&quot;]/div[@class=&quot;pointer d-flex align-items-center justify-content-center mleft5 relative flex-shrink-1 flex-nowrap min-w-0&quot;]/div[@class=&quot;pointer d-flex align-items-center justify-content-center display-value-container flex-shrink-1 flex-nowrap min-w-0&quot;]/span[@class=&quot;material-icons left mleft5 pointer&quot;]</value>
      <webElementGuid>a53cfdc3-b44e-4145-a6c4-a5973bd42fb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainPanel']/div[2]/div[3]/div/div[2]/div/list-drop-down/div/div/span</value>
      <webElementGuid>187d98fd-3b99-4fd2-8b42-0d0d028daaf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target Publication Date-Date'])[3]/following::span[1]</value>
      <webElementGuid>29ca567c-f0c7-4fb1-874f-2c91c15ce5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By:'])[1]/following::span[1]</value>
      <webElementGuid>471ea1b5-4413-4d5d-b844-bbef743bfbe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Modified'])[1]/preceding::span[1]</value>
      <webElementGuid>8a8f9791-3467-44d3-a87b-ba016691080f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::span[1]</value>
      <webElementGuid>4f1382b7-3752-4cea-8de6-b114a0e54c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/list-drop-down/div/div/span</value>
      <webElementGuid>f0242072-6da1-45ee-804c-88ca07e923bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'keyboard_arrow_down' or . = 'keyboard_arrow_down')]</value>
      <webElementGuid>c784b320-6e3f-4e5f-8cfb-9628da8236bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edition Names'])[1]/following::span[2]</value>
      <webElementGuid>b2052a50-7c96-4820-b160-c2f91221efe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supports Revisions'])[1]/following::span[2]</value>
      <webElementGuid>1609e776-fc1d-4365-bc88-99f59dd15083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[2]/preceding::span[3]</value>
      <webElementGuid>3a864e6e-a5df-4cdd-a587-6ba7c0e92669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='keyboard_arrow_down'])[3]/preceding::span[6]</value>
      <webElementGuid>4f6147f8-f56a-4230-9a19-19d5ca0e0948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='keyboard_arrow_down']/parent::*</value>
      <webElementGuid>707cc981-a0c7-43f7-a1b1-5e5dedf567dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>f175f624-75ff-484b-a269-f36c1219cd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' keyboard_arrow_down ' or . = ' keyboard_arrow_down ')]</value>
      <webElementGuid>3b00d42f-2e1f-43c1-8bca-585e282313c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
