<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SingleView-Assignment117</name>
   <tag></tag>
   <elementGuidId>78eb3f7d-45dc-4e5e-b348-fd78763977f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body > app-root > main > loader > div > main-content > div.main-content.sidemenu-expanded > planning-views > div > div.data-container-wrapper-filter-overlay.data-container-wrapper-filter-collapsed > div.left.oauto.data-container.scrollable.data-container-filter-overlay.data-container-filter-collapsed > loader > div > div:nth-child(1) > pane-container > div.is-expanded > div:nth-child(2) > planning-view-item > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Section Title 1'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d9153360-847b-4fda-9e5c-b3c47cd975ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ellipsis</value>
      <webElementGuid>cc446332-3baa-4964-9d61-2f534cac0e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SingleView-Assignment117</value>
      <webElementGuid>c9376880-2052-4e27-ae59-00d82d5fba84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;playbook-theme multiple-products&quot;]/app-root[1]/main[@class=&quot;ng-star-inserted&quot;]/loader[1]/div[1]/side-bar[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;side-bar container expanded&quot;]/div[@class=&quot;container-inner scrollable ng-star-inserted&quot;]/ul[@class=&quot;ng-star-inserted&quot;]/li[@class=&quot;sub-item drag-handle ng-star-inserted&quot;]/div[@class=&quot;navigation-sub-item&quot;]/nav-link[@class=&quot;pointer block mtop5 pleft45 nav-link ng-star-inserted&quot;]/a[1]/span[@class=&quot;ellipsis&quot;]</value>
      <webElementGuid>47a718c2-5b09-447d-8443-df8f9018c3ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Section Title 1'])[1]/following::span[1]</value>
      <webElementGuid>0b228f92-0b8d-420d-87a1-5e806062953c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEFAULT'])[1]/following::span[2]</value>
      <webElementGuid>e7e23c0c-cfc7-4fc7-87c3-9895af6a9d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SingleView-Assignment116'])[1]/preceding::span[1]</value>
      <webElementGuid>2950f323-eecd-486e-8f89-dc323cac9fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show All Views'])[1]/preceding::span[6]</value>
      <webElementGuid>a8a13c08-e7ee-41f7-aff5-a8b1cbd136c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SingleView-Assignment117']/parent::*</value>
      <webElementGuid>42b59f0e-96bc-4424-8fd9-60bb08a3be77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>dfd20f93-9b67-4619-b20f-5c101d47b9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SingleView-Assignment117' or . = 'SingleView-Assignment117')]</value>
      <webElementGuid>33902e1a-b011-4cfb-b685-f05765db9620</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
