<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>topicsRadio</name>
   <tag></tag>
   <elementGuidId>a7392dae-288e-47dc-8d81-5f256696e4af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/main/loader/div/mdl-dialog-host-component/div[2]/create-new-view/div/div[3]/div[3]/div[5]/div[4]/mdl-radio[1][count(. | //*[contains(@class, 'is-checked')]) = count(//*[contains(@class, 'is-checked')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/main/loader/div/mdl-dialog-host-component/div[2]/create-new-view/div/div[3]/div[3]/div[5]/div[4]/mdl-radio[1]</value>
      <webElementGuid>4866591f-c597-4528-ad14-7d2ed50a38a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-checked</value>
      <webElementGuid>64ad8c8c-7394-4fd8-abc8-837babe81c8a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
