<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>playbook9.5-button_Login</name>
   <tag></tag>
   <elementGuidId>b86b20d4-66a3-48b5-ab55-8cc15ed4e705</elementGuidId>
   <imagePath>Screenshots/Targets/Page_AP Storytelling/playbook9.5-button_Login.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-button-toggle-1-button</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_AP Storytelling/playbook9.5-button_Login.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mat-button-toggle-1-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7eaabb38-d1ac-44ed-8354-1096ccd974a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b22d0b58-5910-415c-8058-fefab0e05f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-toggle-button mat-focus-indicator</value>
      <webElementGuid>8a731c90-cd12-4a33-8d76-2d7f2c6ad4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-button-toggle-1-button</value>
      <webElementGuid>69f11bd8-884c-4ca8-9bf9-2b8247b05fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aa63e027-ce22-491e-badf-1cde5503720f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b5283372-67e0-4453-9bbf-da59cf34ed76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mat-button-toggle-group-0</value>
      <webElementGuid>58c7e734-5975-47c5-8cba-5274da3ece78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login </value>
      <webElementGuid>ea93027c-4bba-45d8-add5-62a83012310c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-button-toggle-1-button&quot;)</value>
      <webElementGuid>b2b745e0-d124-43b4-bebe-b90814b7aee2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mat-button-toggle-1-button']</value>
      <webElementGuid>79cec85e-3985-4ea2-ba64-2cc63523dff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-button-toggle[@id='mat-button-toggle-1']/button</value>
      <webElementGuid>5027dc4d-3e67-4ee5-9b73-0d49da369d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember Me'])[1]/following::button[1]</value>
      <webElementGuid>ae9ad4fb-687d-4967-bd61-7eb760dc15fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[2]</value>
      <webElementGuid>9b2ceb45-03c8-4742-9784-d8cc6aad51b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/preceding::button[1]</value>
      <webElementGuid>4b2b6ac7-8c12-4154-ac9c-1f6cf4e1275b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-button-toggle/button</value>
      <webElementGuid>0f2af417-8de5-438a-be52-123bd2e8fa35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'mat-button-toggle-1-button' and @name = 'mat-button-toggle-group-0' and (text() = ' Login ' or . = ' Login ')]</value>
      <webElementGuid>3c743486-82f0-4641-9228-2925db2261dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
